### ISSUE TITLE
NoPoDoFo Lambda: Cannot open shared object file

### ISSUE THREAD

**Issue by AshesOfOwls** [corymickelson/NoPoDoFo#97]
Hi there, thanks for the library.

I am trying to get this set up on AWS lambda however I am running into issues when I require `nopodofo`, it presents me with this error:

```
{"errorMessage":"libidn.so.11: cannot open shared object file: No such file or directory","errorType":"Error","stackTrace":["Module.load (module.js:565:32)","tryModuleLoad (module.js:505:12)","Function.Module._load (module.js:497:3)","Module.require (module.js:596:17)","require (internal/module.js:11:18)","Object.<anonymous> (/var/task/node_modules/nopodofo/dist/index.js:5:14)","Module._compile (module.js:652:30)","Object.Module._extensions..js (module.js:663:10)","Module.load (module.js:565:32)"]}
```

----------------------------

My setup is pretty basic. 

index.js
```javascript
'use strict';

var { Document } = require('nopodofo');

exports.handler = function (event, context, callback) {
  return callback(null, {
    statusCode: 200,
    headers: { 'Content-Type': 'text/html; charset=utf-8' },
    body: event,
  });
};
```

Package.json dependencies:
```json
"nopodofo": "https://github.com/corymickelson/NoPoDoFo/releases/download/v0.7.0/nopodofo-v0.7.0-linux-aws-x64-node-v8.tar.gz",
"nopodofolambda": "^1.0.0-pre"
```

Template.yaml for AWS SAM testing:
```yaml
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description : |
  A signer function

Resources:
  Signer:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs8.10
      Handler: index.handler
```

Testing via: `sam local invoke "Signer" -e event.json`

----------------------

I am not familiar with the shared object files and how nopodofo accesses them from the nopodofolambda package. Is there additional setup I need?
